/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCalendar: typeof import('./src/components/calendar/app-calendar.vue')['default']
    AppCharacterCounter: typeof import('./src/components/forms/app-character-counter.vue')['default']
    AppDataTable: typeof import('./src/components/tables/app-data-table.vue')['default']
    AppDataTableColumn: typeof import('./src/components/tables/app-data-table-column.vue')['default']
    AppDialog: typeof import('./src/components/layout/app-dialog.vue')['default']
    AppDummyText: typeof import('./src/components/text/app-dummy-text.vue')['default']
    AppErrorMessage: typeof import('./src/components/forms/app-error-message.vue')['default']
    AppFooter: typeof import('./src/components/layout/app-footer.vue')['default']
    AppHeader: typeof import('./src/components/layout/app-header.vue')['default']
    AppInputNumber: typeof import('./src/components/forms/app-input-number.vue')['default']
    AppInputText: typeof import('./src/components/forms/app-input-text.vue')['default']
    AppLabel: typeof import('./src/components/forms/app-label.vue')['default']
    AppMultiSelect: typeof import('./src/components/forms/app-multi-select.vue')['default']
    AppSelect: typeof import('./src/components/forms/app-select.vue')['default']
    AppSideNavigation: typeof import('./src/components/layout/app-side-navigation.vue')['default']
    AppTextArea: typeof import('./src/components/forms/app-text-area.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Form: typeof import('@primevue/forms/form')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
