version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HEALTH_ENABLED: 'true'
      KC_LOG_LEVEL: info
    ports:
      - '8080:8080'
    volumes:
      - ./kaboom-export.json:/opt/keycloak/data/import/kaboom-export.json
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health/ready']
      interval: 15s
      timeout: 2s
      retries: 15
    command: start-dev --import-realm
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
